### ISSUE TITLE
Fix the bug in the handling of Horava parameters

### ISSUE THREAD

**Issue by EFTCAMB** [EFTCAMB/EFTCAMB#3]
Now the Horava parameters are not correctly passed from EFTCosmoMC to EFTCAMB.

**Comment by mraveri** [comment]
Shall we add log sampling for eta and lambda?
Is Horava_Solar_system passed correctly?

**Comment by hubinitp** [comment]
Horava_lambda and Horava_eta is log sampled now. 
Horava_Solar_system is passed correctly :)
